# frozen_string_literal: true

# The rmcp version a generated server is built against: one constant, pinned exactly, matching the vendored source.
#
#   ruby -Ilib test/test_versions.rb
require "minitest/autorun"
require "open3"
require "rmcp_dsl"

class TestVersions < Minitest::Test
  ROOT = File.expand_path("..", __dir__)

  def ir(src = "examples/listkit.rmcp.rb") = RmcpDsl.read(File.join(ROOT, src))

  def test_the_generated_cargo_toml_pins_rmcp_exactly
    toml = RmcpDsl::Emit.files(ir, "listkit.rb")["Cargo.toml"]
    assert_includes toml, %(rmcp = { version = "=#{RmcpDsl::RMCP_VERSION}")
    refute_match(/rmcp = \{ version = "\d/, toml, "a caret requirement would let Cargo pick a newer rmcp")
  end

  def test_the_generated_main_says_which_versions_made_it
    main = RmcpDsl::Emit.files(ir, "listkit.rb")["src/main.rs"]
    assert_includes main.lines.first, "Generated by rmcp_dsl #{RmcpDsl::VERSION} for rmcp #{RmcpDsl::RMCP_VERSION} from listkit.rb"
  end

  def test_the_version_option_prints_both_numbers
    out, status = Open3.capture2(RbConfig.ruby, File.join(ROOT, "exe/rmcp_dsl"), "--version")
    assert status.success?
    assert_equal "rmcp_dsl #{RmcpDsl::VERSION} (generates servers for rmcp #{RmcpDsl::RMCP_VERSION})\n", out
  end

  def test_the_gemspec_records_the_rmcp_version
    spec = Gem::Specification.load(File.join(ROOT, "rmcp_dsl.gemspec"))
    assert_equal RmcpDsl::RMCP_VERSION, spec.metadata["rmcp_version"]
  end

  # The compiler is written against the vendored source; a constant that names another version would be a lie.
  def test_the_vendored_source_is_the_pinned_version
    vendored = Dir.glob(File.join(ROOT, "vendor", "rmcp-[0-9]*")).map { |d| File.basename(d).delete_prefix("rmcp-") }
    skip "vendor/ is not part of the gem" if vendored.empty?
    assert_includes vendored, RmcpDsl::RMCP_VERSION, "vendor/ holds rmcp #{vendored.join(', ')} but RMCP_VERSION is #{RmcpDsl::RMCP_VERSION}"
    macros = Dir.glob(File.join(ROOT, "vendor", "rmcp-macros-[0-9]*")).map { |d| File.basename(d).delete_prefix("rmcp-macros-") }
    assert_includes macros, RmcpDsl::RMCP_VERSION, "rmcp-macros is released with rmcp, so its vendored version should match" unless macros.empty?
  end

  def test_the_versions_table_has_a_row_for_the_pinned_version
    readme = File.read(File.join(ROOT, "docs/versions.md"))
    assert_match(/\|\s*0\.1\.x\s*\|\s*#{Regexp.escape(RmcpDsl::RMCP_VERSION)}\s*\|/, readme)
  end

  # The split docs ship in the gem, not just the repository (the gemspec globs docs/**/*.md).
  def test_the_gem_packages_the_docs
    spec = Gem::Specification.load(File.join(ROOT, "rmcp_dsl.gemspec"))
    %w[docs/versions.md docs/cli.md docs/dsl.md docs/body-language.md docs/bindings.md
       docs/editor-support.md docs/coverage.md docs/notifications.md docs/examples.md
       docs/development.md].each do |doc|
      assert_includes spec.files, doc, "#{doc} should ship in the gem"
    end
  end
end
