# typed: strict
# GENERATED by bin/gen_rbi from SIG in schema.rb. Do not edit.

class ServerScope
  sig { params(name: Symbol, blk: T.proc.bind(ParamsScope).void).void }
  def params(name, &blk); end

  sig { params(name: Symbol, blk: T.proc.bind(OutputScope).void).void }
  def output(name, &blk); end

  sig { params(name: Symbol, params: Symbol, description: String, title: T.nilable(String), read_only: T.nilable(T::Boolean), destructive: T.nilable(T::Boolean), idempotent: T.nilable(T::Boolean), open_world: T.nilable(T::Boolean), output: T.nilable(Symbol), icon: T.nilable(String), meta: T.nilable(T::Hash[String, T.untyped]), task: T.nilable(T::Boolean), task_ttl_ms: T.nilable(Integer), task_poll_ms: T.nilable(Integer), updates: T.nilable(T::Array[String]), resource_list_changed: T.nilable(T::Boolean), blk: T.proc.bind(ToolScope).void).void }
  def tool(name, params:, description:, title: nil, read_only: nil, destructive: nil, idempotent: nil, open_world: nil, output: nil, icon: nil, meta: nil, task: nil, task_ttl_ms: nil, task_poll_ms: nil, updates: nil, resource_list_changed: nil, &blk); end

  sig { params(name: Symbol, args: T::Array[Symbol], returns: Symbol, blk: T.untyped).void }
  def helper(name, args:, returns:, &blk); end

  sig { params(name: Symbol, params: Symbol, description: String, title: T.nilable(String), icon: T.nilable(String), meta: T.nilable(T::Hash[String, T.untyped]), blk: T.proc.bind(PromptScope).void).void }
  def prompt(name, params:, description:, title: nil, icon: nil, meta: nil, &blk); end

  sig { params(name: Symbol, uri: String, description: T.nilable(String), mime_type: T.nilable(String), title: T.nilable(String), icon: T.nilable(String), audience: T.nilable(T::Array[String]), priority: T.nilable(T.any(Integer, Float)), params: T.nilable(Symbol), meta: T.nilable(T::Hash[String, T.untyped]), size: T.nilable(Integer), blk: T.proc.bind(ResourceScope).void).void }
  def resource(name, uri:, description: nil, mime_type: nil, title: nil, icon: nil, audience: nil, priority: nil, params: nil, meta: nil, size: nil, &blk); end

  sig { params(kind: Symbol, port: T.nilable(Integer)).void }
  def transport(kind, port: nil); end

  sig { params(crate: String, version: String).void }
  def rust_crate(crate, version); end

  sig { params(code: String).void }
  def rust_item(code); end

  sig { params(name: Symbol, args: T::Array[Symbol], returns: Symbol, from: T.nilable(Symbol)).void }
  def rust_fn(name, args:, returns:, from: nil); end

  sig { params(name: Symbol).void }
  def use_bindings(name); end

  sig { params(path: String, as: Symbol, uses: T.nilable(Symbol)).void }
  def rust_file(path, as:, uses: nil); end

  sig { params(name: Symbol, program: String, args: T::Array[Symbol], returns: Symbol, argv: T.nilable(T::Array[String]), pass: T.nilable(Symbol)).void }
  def cmd_fn(name, program:, args:, returns:, argv: nil, pass: nil); end

  sig { params(name: Symbol, interpreter: String, code: String, args: T::Array[Symbol], returns: Symbol, flag: T.nilable(String)).void }
  def script_fn(name, interpreter:, code:, args:, returns:, flag: nil); end
end

class ParamsScope
  sig { params(name: Symbol, type: T.any(Symbol, T.class_of(RmcpDsl::Opaque)), description: T.nilable(String), optional: T.nilable(T::Boolean), default: T.nilable(T.any(String, Integer, Float, T::Boolean)), min: T.nilable(T.any(Integer, Float)), max: T.nilable(T.any(Integer, Float)), min_length: T.nilable(Integer), max_length: T.nilable(Integer), pattern: T.nilable(String), enum: T.nilable(T::Array[String]), format: T.nilable(Symbol), min_items: T.nilable(Integer), max_items: T.nilable(Integer)).void }
  def field(name, type, description: nil, optional: nil, default: nil, min: nil, max: nil, min_length: nil, max_length: nil, pattern: nil, enum: nil, format: nil, min_items: nil, max_items: nil); end

  sig { params(type: Symbol).returns(Symbol) }
  def map(type); end

  sig { params(type: Symbol).returns(Symbol) }
  def list(type); end
end

class OutputScope
  sig { params(name: Symbol, type: T.any(Symbol, T.class_of(RmcpDsl::Opaque)), description: T.nilable(String), optional: T.nilable(T::Boolean), default: T.nilable(T.any(String, Integer, Float, T::Boolean)), min: T.nilable(T.any(Integer, Float)), max: T.nilable(T.any(Integer, Float)), min_length: T.nilable(Integer), max_length: T.nilable(Integer), pattern: T.nilable(String), enum: T.nilable(T::Array[String]), format: T.nilable(Symbol), min_items: T.nilable(Integer), max_items: T.nilable(Integer)).void }
  def field(name, type, description: nil, optional: nil, default: nil, min: nil, max: nil, min_length: nil, max_length: nil, pattern: nil, enum: nil, format: nil, min_items: nil, max_items: nil); end

  sig { params(type: Symbol).returns(Symbol) }
  def map(type); end

  sig { params(type: Symbol).returns(Symbol) }
  def list(type); end
end

class ToolScope
  sig { params(blk: T.untyped).void }
  def body(&blk); end

  sig { params(name: Symbol, args: T.untyped).returns(T.untyped) }
  def rust(name, *args); end

  sig { params(name: Symbol, fields: T.untyped).returns(T.untyped) }
  def result(name, **fields); end

  sig { params(text: String, audience: T.nilable(T::Array[Symbol]), priority: T.nilable(T.any(Integer, Float))).returns(ContentBlock) }
  def text(text, audience: nil, priority: nil); end

  sig { params(data: String, mime_type: String, audience: T.nilable(T::Array[Symbol]), priority: T.nilable(T.any(Integer, Float))).returns(ContentBlock) }
  def image(data, mime_type, audience: nil, priority: nil); end

  sig { params(data: String, mime_type: String, audience: T.nilable(T::Array[Symbol]), priority: T.nilable(T.any(Integer, Float))).returns(ContentBlock) }
  def audio(data, mime_type, audience: nil, priority: nil); end

  sig { params(uri: String, name: String, title: T.nilable(String), description: T.nilable(String), mime_type: T.nilable(String), size: T.nilable(Integer), audience: T.nilable(T::Array[Symbol]), priority: T.nilable(T.any(Integer, Float))).returns(ContentBlock) }
  def resource_link(uri, name:, title: nil, description: nil, mime_type: nil, size: nil, audience: nil, priority: nil); end

  sig { params(uri: String, text: String, mime_type: T.nilable(String), audience: T.nilable(T::Array[Symbol]), priority: T.nilable(T.any(Integer, Float))).returns(ContentBlock) }
  def embedded_text(uri, text, mime_type: nil, audience: nil, priority: nil); end

  sig { params(uri: String, data: String, mime_type: T.nilable(String), audience: T.nilable(T::Array[Symbol]), priority: T.nilable(T.any(Integer, Float))).returns(ContentBlock) }
  def embedded_blob(uri, data, mime_type: nil, audience: nil, priority: nil); end
end

class PromptScope
  sig { params(blk: T.untyped).void }
  def body(&blk); end

  sig { params(role: Symbol, blk: T.untyped).void }
  def message(role, &blk); end

  sig { params(name: Symbol, args: T.untyped).returns(T.untyped) }
  def rust(name, *args); end

  sig { params(name: Symbol, fields: T.untyped).returns(T.untyped) }
  def result(name, **fields); end
end

class ResourceScope
  sig { params(blk: T.untyped).void }
  def body(&blk); end

  sig { params(name: Symbol, args: T.untyped).returns(T.untyped) }
  def rust(name, *args); end

  sig { params(name: Symbol, fields: T.untyped).returns(T.untyped) }
  def result(name, **fields); end
end

sig { params(name: String, version: String, instructions: T.nilable(String), title: T.nilable(String), description: T.nilable(String), website_url: T.nilable(String), icon: T.nilable(String), page_size: T.nilable(Integer), blk: T.proc.bind(ServerScope).void).void }
def server(name, version:, instructions: nil, title: nil, description: nil, website_url: nil, icon: nil, page_size: nil, &blk); end

# What text(...), image(...) and the other content builders return.
class ContentBlock; end

module Rust
  sig { params(value: Integer).returns(Integer) }
  def self.Int32(value); end

  sig { params(value: Integer).returns(Integer) }
  def self.Int64(value); end
end

# The macros a binding file (bindings/*.rb) uses; the compiler reads them with Prism.
module RmcpDsl
  # A type a binding owns; the compiler reads `type_rust` with Prism.
  class Opaque
    sig { params(rust: String, wire: T::Boolean).void }
    def self.type_rust(rust, wire: false); end
  end

  module BindingDsl
    sig { params(name: String, version: String).void }
    def crate(name, version); end

    sig { params(template: String).void }
    def rust(template); end

    sig { params(reason: String).void }
    def no_reference(reason); end

    sig { params(method: Symbol, args: T.untyped, expect: T.untyped).void }
    def example(method, *args, expect:); end
  end
end

# Sorbet only knows Integer; the compiler reads the names to learn the width.
I32 = T.type_alias { Integer }
I64 = T.type_alias { Integer }
