# typed: true
# (Sorbet knows the helpers from sorbet/rbi/rmcp_dsl/dsl_helpers.rbi, generated by `make rbi-helpers`.)
# webkit: the job of examples/fetchkit.rmcp.rb written mostly in Ruby. A request guard (valid URL, http or https
# only, no credentials, every resolved address public) and HTML selectors, using bindings for the parts
# that need Rust libraries: Url (the url crate), Net (std::net) and Html (the scraper crate). The bindings
# return nil for "does not parse" or "does not resolve"; this file decides what that means. The guard is
# three helpers, so each fetching tool states it once instead of repeating it.
#
# Limits, compared with fetchkit: redirects are not followed.
server "webkit", version: "0.1.0" do
  use_bindings :html
  use_bindings :url
  use_bindings :net

  # curl is told to connect to the address the guard already checked, so it cannot resolve the name again
  # to something else. An empty first argument means "no pin" (the URL already is an address).
  script_fn :curl_pinned, interpreter: "sh", args: [:string, :string], returns: :string, code: <<~'SH'
    if [ -n "$1" ]; then
      exec curl -q -sS -f -g --proto =http,https --max-redirs 0 --max-time 8 --connect-timeout 5 --max-filesize 1000000 --no-netrc -A webkit/0.1 --resolve "$1" --url "$2"
    else
      exec curl -q -sS -f -g --proto =http,https --max-redirs 0 --max-time 8 --connect-timeout 5 --max-filesize 1000000 --no-netrc -A webkit/0.1 --url "$2"
    fi
  SH

  # Half one of the guard: a valid http(s) URL with no credentials and a host. Returns the host, without
  # the brackets of an IPv6 literal. A helper can only call helpers declared above it, so there is no recursion.
  helper :checked_host, args: [:string], returns: :string do |url|
    raise "not a valid URL: #{url}" unless Url.valid?(url)
    raise "credentials in URLs are not supported" if Url.credentials?(url)
    scheme = Url.scheme(url) || raise("not a valid URL: #{url}")
    raise "only http and https are allowed, not #{scheme}" unless scheme == "http" || scheme == "https"
    (Url.host(url) || raise("URL has no host")).delete("[]")
  end

  # Half two: resolve the host and require every address to be public. Uses the helper above.
  helper :checked_addresses, args: [:string], returns: :string_list do |url|
    host = checked_host(url)
    addrs = Net.addresses(host) || raise("cannot resolve #{host}")
    raise "#{host} has no addresses" if addrs.empty?
    raise "blocked address for #{host}: not a public address" unless addrs.all? { |a| Net.public_address?(a) }
    addrs
  end

  # curl's --resolve argument for the address to pin: prefer IPv4, bracket an IPv6 address, and pin nothing
  # when the URL already is an address.
  helper :pin_arg, args: [:string, :i64, :string_list], returns: :string do |host, port, addrs|
    addr = addrs.find { |a| !a.include?(":") } || (addrs.first || raise("#{host} has no addresses"))
    addr == host ? "" : (addr.include?(":") ? "#{host}:#{port}:[#{addr}]" : "#{host}:#{port}:#{addr}")
  end

  # `endpoint(host, port, scheme:)` renders the URL a request would use. `port` is nil-able (a URL with no
  # explicit port), and `scheme:` is an optional keyword argument whose literal default is "http"; a call may
  # pass keyword arguments in any order or leave an optional one out for its default.
  helper :endpoint, args: [:string, :i64?], returns: :string, kw: { scheme: [:string, false] } do |host, port, scheme: "http"|
    "#{scheme}://#{host}:#{port || 80}"
  end

  params :UrlParams do
    field :url, :string, description: "Absolute http or https URL"
  end

  params :HtmlParams do
    field :html, :string, description: "HTML text"
    field :css, :string, description: "CSS selector, for example h1 or ul > li"
  end

  params :AttrParams do
    field :html, :string, description: "HTML text"
    field :css, :string, description: "CSS selector"
    field :name, :string, description: "Attribute name, for example href"
  end

  params :CssParams do
    field :css, :string, description: "A CSS selector to check"
  end

  params :JoinParams do
    field :base, :string, description: "The page URL"
    field :href, :string, description: "A link found on that page"
  end

  params :IpParams do
    field :ip, :string, description: "An IP address"
  end

  tool :check_url, params: :UrlParams, description: "Run the request guard on a URL without fetching it: the address it would connect to, or why it is refused",
                   title: "Check a URL", read_only: true, open_world: false do
    body do |url|
      "ok: #{checked_addresses(url).first || "-"}"
    end
  end

  tool :fetch_page, params: :UrlParams, description: "GET a public http(s) page (no redirects). The address is checked first and curl is pinned to it. Returns untrusted content.",
                    title: "Fetch a page", read_only: true, open_world: true do
    body do |url|
      host = checked_host(url)
      addrs = checked_addresses(url)
      port = Url.port(url) || raise("URL has no port")
      page = rust(:curl_pinned, pin_arg(host, port, addrs), url)
      page.start_with?("error:") ? raise(page) : page
    end
  end

  tool :select_html, params: :HtmlParams, description: "The text of every element matching a CSS selector, one per line; an invalid selector is an error",
                     title: "Select from HTML", read_only: true, open_world: false do
    body do |html, css|
      found = Html.select(html, css) || raise("invalid CSS selector: #{css}")
      found.empty? ? "(no matches)" : found.join("\n")
    end
  end

  tool :attr_html, params: :AttrParams, description: "One attribute of every matching element that has it; an invalid selector just finds nothing",
                   title: "Attribute from HTML", read_only: true, open_world: false do
    body do |html, css, name|
      values = Html.attr(html, css, name) || []
      values.empty? ? "(none)" : values.join("\n")
    end
  end

  tool :selector_ok, params: :CssParams, description: "Is this a valid CSS selector",
                     title: "Check a selector", read_only: true, open_world: false do
    body do |css|
      Html.valid_selector?(css) ? "valid" : "invalid"
    end
  end

  tool :absolute, params: :JoinParams, description: "Resolve a link against the page URL, as a browser does",
                  title: "Resolve a link", read_only: true, open_world: false do
    body do |base, href|
      Url.join(base, href) || "(invalid)"
    end
  end

  tool :host_of, params: :UrlParams, description: "The host of a URL, lower-cased, or (none)",
                 title: "Host of a URL", read_only: true, open_world: false do
    body do |url|
      Url.host(url) || "(none)"
    end
  end

  tool :is_public, params: :IpParams, description: "Is this a globally routable address (not loopback, private, link-local, ...)",
                   title: "Is an address public", read_only: true, open_world: false do
    body do |ip|
      Net.public_address?(ip) ? "public" : "not public"
    end
  end

  # Calls the nil-able-parameter helper twice: once with the keyword given and once with it left out for the
  # default, so both call paths are covered by the e2e run.
  tool :endpoint_of, params: :UrlParams, description: "The endpoint (scheme, host and port) a URL would use",
                 title: "Endpoint of a URL", read_only: true, open_world: false do
    body do |url|
      host = checked_host(url)
      port = Url.port(url)
      explicit = endpoint(host, port, scheme: "https")
      fallback = endpoint(host, port)
      "#{explicit} #{fallback}"
    end
  end

  transport :stdio
end
