# typed: strict
# GENERATED by `rmcp_dsl rbi` from the helpers the DSL files declare. Do not edit.

class ServerScope
  sig { params(url: String).returns(T::Array[String]) }
  def checked_addresses(url); end

  sig { params(url: String).returns(String) }
  def checked_host(url); end

  sig { params(host: String, port: Integer, addrs: T::Array[String]).returns(String) }
  def pin_arg(host, port, addrs); end
end

class ToolScope
  sig { params(url: String).returns(T::Array[String]) }
  def checked_addresses(url); end

  sig { params(url: String).returns(String) }
  def checked_host(url); end

  sig { params(host: String, port: Integer, addrs: T::Array[String]).returns(String) }
  def pin_arg(host, port, addrs); end
end

class PromptScope
  sig { params(url: String).returns(T::Array[String]) }
  def checked_addresses(url); end

  sig { params(url: String).returns(String) }
  def checked_host(url); end

  sig { params(host: String, port: Integer, addrs: T::Array[String]).returns(String) }
  def pin_arg(host, port, addrs); end
end

class ResourceScope
  sig { params(url: String).returns(T::Array[String]) }
  def checked_addresses(url); end

  sig { params(url: String).returns(String) }
  def checked_host(url); end

  sig { params(host: String, port: Integer, addrs: T::Array[String]).returns(String) }
  def pin_arg(host, port, addrs); end
end
