// GENERATED by bin/gen_shim_tests from spec/shims/*.yml and bindings/*.rb. Do not edit.

fn str_to_i(s: &str, at: &str) -> Result<i64, String> {
    let mut chars = s
        .trim_start_matches(|c: char| matches!(c, ' ' | '\t' | '\n' | '\u{b}' | '\u{c}' | '\r'))
        .chars()
        .peekable();
    let negative = match chars.peek() {
        Some('-') => {
            chars.next();
            true
        }
        Some('+') => {
            chars.next();
            false
        }
        _ => false,
    };
    let mut value: i128 = 0;
    let mut overflow = false;
    let mut after_digit = false;
    while let Some(&c) = chars.peek() {
        if c.is_ascii_digit() {
            chars.next();
            after_digit = true;
            if !overflow {
                match value.checked_mul(10).and_then(|v| v.checked_add(c as i128 - '0' as i128)) {
                    Some(v) if v <= i64::MAX as i128 + 1 => value = v,
                    _ => overflow = true,
                }
            }
        } else if c == '_' && after_digit {
            chars.next();
            match chars.peek() {
                Some(d) if d.is_ascii_digit() => {}
                _ => break,
            }
        } else {
            break;
        }
    }
    let signed = if negative { -value } else { value };
    if overflow || signed > i64::MAX as i128 || signed < i64::MIN as i128 {
        return Err(format!(
            "error: integer overflow at {at}: {s:?} does not fit in i64 ({}..={}). Fix: check the length of the input before converting it.",
            i64::MIN,
            i64::MAX
        ));
    }
    Ok(signed as i64)
}


fn str_to_int(s: &str, at: &str) -> Result<i64, String> {
    let t = s.trim_matches(|c: char| matches!(c, ' ' | '\t' | '\n' | '\u{b}' | '\u{c}' | '\r'));
    let (negative, digits) = match t.as_bytes().first() {
        Some(b'-') => (true, &t[1..]),
        Some(b'+') => (false, &t[1..]),
        _ => (false, t),
    };
    let well_formed = !digits.is_empty()
        && !digits.starts_with('_')
        && !digits.ends_with('_')
        && !digits.contains("__")
        && digits.chars().all(|c| c.is_ascii_digit() || c == '_');
    if !well_formed {
        return Err(format!("error: invalid value for Integer(): {s:?} at {at}"));
    }
    let mut value: i128 = 0;
    for c in digits.chars().filter(|c| *c != '_') {
        match value.checked_mul(10).and_then(|v| v.checked_add(c as i128 - '0' as i128)) {
            Some(v) if v <= i64::MAX as i128 + 1 => value = v,
            _ => {
                return Err(format!(
                    "error: integer overflow at {at}: {s:?} does not fit in i64 ({}..={}). Fix: check the length of the input before converting it.",
                    i64::MIN,
                    i64::MAX
                ))
            }
        }
    }
    let signed = if negative { -value } else { value };
    if signed > i64::MAX as i128 || signed < i64::MIN as i128 {
        return Err(format!(
            "error: integer overflow at {at}: {s:?} does not fit in i64 ({}..={}). Fix: check the length of the input before converting it.",
            i64::MIN,
            i64::MAX
        ));
    }
    Ok(signed as i64)
}


fn heck_snake_case(s: &str) -> String {
    heck::ToSnakeCase::to_snake_case(s)
}

fn heck_kebab_case(s: &str) -> String {
    heck::ToKebabCase::to_kebab_case(s)
}

fn heck_upper_camel_case(s: &str) -> String {
    heck::ToUpperCamelCase::to_upper_camel_case(s)
}

fn html_valid_selector_p(css: &str) -> bool {
    scraper::Selector::parse(css).is_ok()
}

fn html_select(html: &str, css: &str) -> Option<Vec<String>> {
    scraper::Selector::parse(css).ok().map(|sel| scraper::Html::parse_document(html).select(&sel).map(|el| el.text().collect::<String>().split_whitespace().collect::<Vec<_>>().join(" ")).collect::<Vec<String>>())
}

fn html_attr(html: &str, css: &str, name: &str) -> Option<Vec<String>> {
    scraper::Selector::parse(css).ok().map(|sel| scraper::Html::parse_document(html).select(&sel).filter_map(|el| el.value().attr(name).map(|v| v.to_string())).collect::<Vec<String>>())
}

fn net_addresses(host: &str) -> Option<Vec<String>> {
    std::net::ToSocketAddrs::to_socket_addrs(&(host, 0u16)).ok().map(|it| it.map(|a| a.ip().to_string()).collect::<Vec<String>>())
}

fn net_public_address_p(ip: &str) -> bool {
    ip.parse::<std::net::IpAddr>().map(|a| { let a = match a { std::net::IpAddr::V6(v6) => v6.to_ipv4_mapped().map(std::net::IpAddr::V4).unwrap_or(a), _ => a }; match a { std::net::IpAddr::V4(v4) => { let o = v4.octets(); !(v4.is_loopback() || v4.is_private() || v4.is_link_local() || v4.is_unspecified() || v4.is_broadcast() || v4.is_documentation() || v4.is_multicast() || o[0] == 0 || (o[0] == 100 && (o[1] & 0xC0) == 64) || o[0] >= 240) } std::net::IpAddr::V6(v6) => { let s = v6.segments(); !(v6.is_loopback() || v6.is_unspecified() || v6.is_multicast() || (s[0] & 0xfe00) == 0xfc00 || (s[0] & 0xffc0) == 0xfe80) } } }).unwrap_or(false)
}

fn url_valid_p(u: &str) -> bool {
    url::Url::parse(u).is_ok()
}

fn url_credentials_p(u: &str) -> bool {
    url::Url::parse(u).map(|x| !x.username().is_empty() || x.password().is_some()).unwrap_or(false)
}

fn url_scheme(u: &str) -> Option<String> {
    url::Url::parse(u).ok().map(|x| x.scheme().to_string())
}

fn url_host(u: &str) -> Option<String> {
    url::Url::parse(u).ok().and_then(|x| x.host_str().map(|h| h.to_string()))
}

fn url_port(u: &str) -> Option<i64> {
    url::Url::parse(u).ok().and_then(|x| x.port_or_known_default()).map(|p| p as i64)
}

fn url_path(u: &str) -> Option<String> {
    url::Url::parse(u).ok().map(|x| x.path().to_string())
}

fn url_join(base: &str, rel: &str) -> Option<String> {
    url::Url::parse(base).ok().and_then(|b| b.join(rel).ok()).map(|j| j.to_string())
}

#[test]
fn string_strip_0() {
    let s: &str = "";
    assert_eq!(s.trim_matches(|c: char| matches!(c, '\u{0}' | '\t' | '\n' | '\u{b}' | '\u{c}' | '\r' | ' ')), "");
}

#[test]
fn string_strip_1() {
    let s: &str = "  hi \u{a}";
    assert_eq!(s.trim_matches(|c: char| matches!(c, '\u{0}' | '\t' | '\n' | '\u{b}' | '\u{c}' | '\r' | ' ')), "hi");
}

#[test]
fn string_strip_2() {
    let s: &str = "\u{b}x\u{b}";
    assert_eq!(s.trim_matches(|c: char| matches!(c, '\u{0}' | '\t' | '\n' | '\u{b}' | '\u{c}' | '\r' | ' ')), "x");
}

#[test]
fn string_strip_3() {
    let s: &str = "\u{a0}x\u{a0}";
    assert_eq!(s.trim_matches(|c: char| matches!(c, '\u{0}' | '\t' | '\n' | '\u{b}' | '\u{c}' | '\r' | ' ')), "\u{a0}x\u{a0}");
}

#[test]
fn string_strip_4() {
    let s: &str = "\u{65e5}\u{672c} ";
    assert_eq!(s.trim_matches(|c: char| matches!(c, '\u{0}' | '\t' | '\n' | '\u{b}' | '\u{c}' | '\r' | ' ')), "\u{65e5}\u{672c}");
}

#[test]
fn rust_str_strip_0() {
    let s: &str = "";
    assert_eq!(s.trim(), "");
}

#[test]
fn rust_str_strip_1() {
    let s: &str = "  hi \u{a}";
    assert_eq!(s.trim(), "hi");
}

#[test]
fn rust_str_strip_2() {
    let s: &str = "\u{b}x\u{b}";
    assert_eq!(s.trim(), "x");
}

#[test]
fn rust_str_strip_3() {
    let s: &str = "\u{a0}x\u{a0}";
    assert_eq!(s.trim(), "x");
}

#[test]
fn rust_str_strip_4() {
    let s: &str = "\u{3000}\u{65e5}\u{672c}\u{3000}";
    assert_eq!(s.trim(), "\u{65e5}\u{672c}");
}

#[test]
fn rust_str_strip_5() {
    let s: &str = "\u{0}x\u{0}";
    assert_eq!(s.trim(), "\u{0}x\u{0}");
}

#[test]
fn string_downcase_0() {
    let s: &str = "";
    assert_eq!(s.to_lowercase(), "");
}

#[test]
fn string_downcase_1() {
    let s: &str = "ABC";
    assert_eq!(s.to_lowercase(), "abc");
}

#[test]
fn string_downcase_2() {
    let s: &str = "\u{c9}COLE";
    assert_eq!(s.to_lowercase(), "\u{e9}cole");
}

#[test]
fn rust_str_to_lowercase_0() {
    let s: &str = "";
    assert_eq!(s.to_lowercase(), "");
}

#[test]
fn rust_str_to_lowercase_1() {
    let s: &str = "ABC";
    assert_eq!(s.to_lowercase(), "abc");
}

#[test]
fn rust_str_to_lowercase_2() {
    let s: &str = "\u{c9}COLE";
    assert_eq!(s.to_lowercase(), "\u{e9}cole");
}

#[test]
fn string_length_0() {
    let s: &str = "";
    assert_eq!(s.chars().count(), 0);
}

#[test]
fn string_length_1() {
    let s: &str = "abc";
    assert_eq!(s.chars().count(), 3);
}

#[test]
fn string_length_2() {
    let s: &str = "h\u{e9}llo";
    assert_eq!(s.chars().count(), 5);
}

#[test]
fn string_length_3() {
    let s: &str = "\u{65e5}\u{672c}";
    assert_eq!(s.chars().count(), 2);
}

#[test]
fn rust_str_len_0() {
    let s: &str = "";
    assert_eq!(s.len(), 0);
}

#[test]
fn rust_str_len_1() {
    let s: &str = "abc";
    assert_eq!(s.len(), 3);
}

#[test]
fn rust_str_len_2() {
    let s: &str = "h\u{e9}llo";
    assert_eq!(s.len(), 6);
}

#[test]
fn rust_str_len_3() {
    let s: &str = "\u{65e5}\u{672c}";
    assert_eq!(s.len(), 6);
}

#[test]
fn string_gsub_string_string_0() {
    let s: &str = "";
    let pat: &str = "a";
    let repl: &str = "b";
    assert_eq!(s.replace(pat, repl), "");
}

#[test]
fn string_gsub_string_string_1() {
    let s: &str = "aXa";
    let pat: &str = "a";
    let repl: &str = "b";
    assert_eq!(s.replace(pat, repl), "bXb");
}

#[test]
fn string_gsub_string_string_2() {
    let s: &str = "a.a";
    let pat: &str = ".";
    let repl: &str = "!";
    assert_eq!(s.replace(pat, repl), "a!a");
}

#[test]
fn string_gsub_string_string_3() {
    let s: &str = "\u{65e5}\u{672c}\u{65e5}";
    let pat: &str = "\u{65e5}";
    let repl: &str = "x";
    assert_eq!(s.replace(pat, repl), "x\u{672c}x");
}

#[test]
fn string_gsub_string_string_4() {
    let s: &str = "$a$";
    let pat: &str = "a";
    let repl: &str = "$1";
    assert_eq!(s.replace(pat, repl), "$$1$");
}

#[test]
fn string_gsub_string_string_5() {
    let s: &str = "x";
    let pat: &str = "";
    let repl: &str = "-";
    assert_eq!(s.replace(pat, repl), "-x-");
}

#[test]
fn string_sub_string_string_0() {
    let s: &str = "";
    let pat: &str = "a";
    let repl: &str = "b";
    assert_eq!(s.replacen(pat, repl, 1), "");
}

#[test]
fn string_sub_string_string_1() {
    let s: &str = "aaa";
    let pat: &str = "a";
    let repl: &str = "b";
    assert_eq!(s.replacen(pat, repl, 1), "baa");
}

#[test]
fn string_sub_string_string_2() {
    let s: &str = "xyz";
    let pat: &str = "q";
    let repl: &str = "b";
    assert_eq!(s.replacen(pat, repl, 1), "xyz");
}

#[test]
fn string_sub_string_string_3() {
    let s: &str = "\u{65e5}\u{672c}\u{65e5}";
    let pat: &str = "\u{65e5}";
    let repl: &str = "x";
    assert_eq!(s.replacen(pat, repl, 1), "x\u{672c}\u{65e5}");
}

#[test]
fn string_gsub_regex_string_0() {
    let s: &str = "";
    let pat: &str = "(?m)x";
    let repl: &str = "y";
    assert_eq!(regex::Regex::new(pat).unwrap().replace_all(s, regex::NoExpand(repl)).into_owned(), "");
}

#[test]
fn string_gsub_regex_string_1() {
    let s: &str = "a1b22";
    let pat: &str = "(?m)[0-9]+";
    let repl: &str = "#";
    assert_eq!(regex::Regex::new(pat).unwrap().replace_all(s, regex::NoExpand(repl)).into_owned(), "a#b#");
}

#[test]
fn string_gsub_regex_string_2() {
    let s: &str = "a\u{a}b";
    let pat: &str = "(?m)^b";
    let repl: &str = "X";
    assert_eq!(regex::Regex::new(pat).unwrap().replace_all(s, regex::NoExpand(repl)).into_owned(), "a\u{a}X");
}

#[test]
fn string_gsub_regex_string_3() {
    let s: &str = "cost";
    let pat: &str = "(?m)o";
    let repl: &str = "$";
    assert_eq!(regex::Regex::new(pat).unwrap().replace_all(s, regex::NoExpand(repl)).into_owned(), "c$st");
}

#[test]
fn string_gsub_regex_string_4() {
    let s: &str = "a\u{663}b";
    let pat: &str = "(?m)[0-9]";
    let repl: &str = "#";
    assert_eq!(regex::Regex::new(pat).unwrap().replace_all(s, regex::NoExpand(repl)).into_owned(), "a\u{663}b");
}

#[test]
fn string_gsub_regex_string_5() {
    let s: &str = "h\u{e9}llo";
    let pat: &str = "(?m)[^a-z]";
    let repl: &str = "_";
    assert_eq!(regex::Regex::new(pat).unwrap().replace_all(s, regex::NoExpand(repl)).into_owned(), "h_llo");
}

#[test]
fn string_gsub_regex_string_6() {
    let s: &str = "--a--";
    let pat: &str = "(?m)\\A-+|-+\\z";
    let repl: &str = "";
    assert_eq!(regex::Regex::new(pat).unwrap().replace_all(s, regex::NoExpand(repl)).into_owned(), "a");
}

#[test]
fn string_sub_regex_string_0() {
    let s: &str = "";
    let pat: &str = "(?m)x";
    let repl: &str = "y";
    assert_eq!(regex::Regex::new(pat).unwrap().replace(s, regex::NoExpand(repl)).into_owned(), "");
}

#[test]
fn string_sub_regex_string_1() {
    let s: &str = "a1b22";
    let pat: &str = "(?m)[0-9]+";
    let repl: &str = "#";
    assert_eq!(regex::Regex::new(pat).unwrap().replace(s, regex::NoExpand(repl)).into_owned(), "a#b22");
}

#[test]
fn string_sub_regex_string_2() {
    let s: &str = "abc";
    let pat: &str = "(?m)z";
    let repl: &str = "y";
    assert_eq!(regex::Regex::new(pat).unwrap().replace(s, regex::NoExpand(repl)).into_owned(), "abc");
}

#[test]
fn string_sub_regex_string_3() {
    let s: &str = "x\u{a}y";
    let pat: &str = "(?m)^y";
    let repl: &str = "Z";
    assert_eq!(regex::Regex::new(pat).unwrap().replace(s, regex::NoExpand(repl)).into_owned(), "x\u{a}Z");
}

#[test]
fn string_split_length_0() {
    let s: &str = "";
    assert_eq!(s.split(|c: char| matches!(c, ' ' | '\t' | '\n' | '\u{b}' | '\u{c}' | '\r')).filter(|w| !w.is_empty()).count() as i64, 0);
}

#[test]
fn string_split_length_1() {
    let s: &str = "one";
    assert_eq!(s.split(|c: char| matches!(c, ' ' | '\t' | '\n' | '\u{b}' | '\u{c}' | '\r')).filter(|w| !w.is_empty()).count() as i64, 1);
}

#[test]
fn string_split_length_2() {
    let s: &str = "  a  b\u{9}c\u{a}";
    assert_eq!(s.split(|c: char| matches!(c, ' ' | '\t' | '\n' | '\u{b}' | '\u{c}' | '\r')).filter(|w| !w.is_empty()).count() as i64, 3);
}

#[test]
fn string_split_length_3() {
    let s: &str = "a\u{a0}b";
    assert_eq!(s.split(|c: char| matches!(c, ' ' | '\t' | '\n' | '\u{b}' | '\u{c}' | '\r')).filter(|w| !w.is_empty()).count() as i64, 1);
}

#[test]
fn string_split_length_4() {
    let s: &str = "a\u{0}b";
    assert_eq!(s.split(|c: char| matches!(c, ' ' | '\t' | '\n' | '\u{b}' | '\u{c}' | '\r')).filter(|w| !w.is_empty()).count() as i64, 1);
}

#[test]
fn string_split_length_5() {
    let s: &str = "\u{65e5}\u{672c} \u{8a9e}";
    assert_eq!(s.split(|c: char| matches!(c, ' ' | '\t' | '\n' | '\u{b}' | '\u{c}' | '\r')).filter(|w| !w.is_empty()).count() as i64, 2);
}

#[test]
fn string_split_length_6() {
    let s: &str = " \u{b} x \u{c} ";
    assert_eq!(s.split(|c: char| matches!(c, ' ' | '\t' | '\n' | '\u{b}' | '\u{c}' | '\r')).filter(|w| !w.is_empty()).count() as i64, 1);
}

#[test]
fn string_capitalize_0() {
    let s: &str = "";
    assert_eq!({ let mut cs = s.chars(); match cs.next() { Some(f) => f.to_uppercase().collect::<String>() + &cs.as_str().to_lowercase(), None => String::new() } }, "");
}

#[test]
fn string_capitalize_1() {
    let s: &str = "hello";
    assert_eq!({ let mut cs = s.chars(); match cs.next() { Some(f) => f.to_uppercase().collect::<String>() + &cs.as_str().to_lowercase(), None => String::new() } }, "Hello");
}

#[test]
fn string_capitalize_2() {
    let s: &str = "HELLO";
    assert_eq!({ let mut cs = s.chars(); match cs.next() { Some(f) => f.to_uppercase().collect::<String>() + &cs.as_str().to_lowercase(), None => String::new() } }, "Hello");
}

#[test]
fn string_capitalize_3() {
    let s: &str = "\u{e9}COLE";
    assert_eq!({ let mut cs = s.chars(); match cs.next() { Some(f) => f.to_uppercase().collect::<String>() + &cs.as_str().to_lowercase(), None => String::new() } }, "\u{c9}cole");
}

#[test]
fn string_capitalize_4() {
    let s: &str = "1abc";
    assert_eq!({ let mut cs = s.chars(); match cs.next() { Some(f) => f.to_uppercase().collect::<String>() + &cs.as_str().to_lowercase(), None => String::new() } }, "1abc");
}

#[test]
fn string_capitalize_5() {
    let s: &str = "\u{65e5}\u{672c}";
    assert_eq!({ let mut cs = s.chars(); match cs.next() { Some(f) => f.to_uppercase().collect::<String>() + &cs.as_str().to_lowercase(), None => String::new() } }, "\u{65e5}\u{672c}");
}

#[test]
fn string_start_with_0() {
    let s: &str = "";
    let pre: &str = "";
    assert_eq!(s.starts_with(pre), true);
}

#[test]
fn string_start_with_1() {
    let s: &str = "";
    let pre: &str = "a";
    assert_eq!(s.starts_with(pre), false);
}

#[test]
fn string_start_with_2() {
    let s: &str = "abc";
    let pre: &str = "";
    assert_eq!(s.starts_with(pre), true);
}

#[test]
fn string_start_with_3() {
    let s: &str = "https://x";
    let pre: &str = "https";
    assert_eq!(s.starts_with(pre), true);
}

#[test]
fn string_start_with_4() {
    let s: &str = "abc";
    let pre: &str = "abcd";
    assert_eq!(s.starts_with(pre), false);
}

#[test]
fn string_start_with_5() {
    let s: &str = "ABC";
    let pre: &str = "a";
    assert_eq!(s.starts_with(pre), false);
}

#[test]
fn string_start_with_6() {
    let s: &str = "\u{65e5}\u{672c}\u{8a9e}";
    let pre: &str = "\u{65e5}\u{672c}";
    assert_eq!(s.starts_with(pre), true);
}

#[test]
fn string_end_with_0() {
    let s: &str = "";
    let suf: &str = "";
    assert_eq!(s.ends_with(suf), true);
}

#[test]
fn string_end_with_1() {
    let s: &str = "";
    let suf: &str = "a";
    assert_eq!(s.ends_with(suf), false);
}

#[test]
fn string_end_with_2() {
    let s: &str = "abc";
    let suf: &str = "";
    assert_eq!(s.ends_with(suf), true);
}

#[test]
fn string_end_with_3() {
    let s: &str = "a/b/";
    let suf: &str = "/";
    assert_eq!(s.ends_with(suf), true);
}

#[test]
fn string_end_with_4() {
    let s: &str = "abc";
    let suf: &str = "xabc";
    assert_eq!(s.ends_with(suf), false);
}

#[test]
fn string_end_with_5() {
    let s: &str = "\u{65e5}\u{672c}\u{8a9e}";
    let suf: &str = "\u{672c}\u{8a9e}";
    assert_eq!(s.ends_with(suf), true);
}

#[test]
fn string_include_0() {
    let s: &str = "";
    let sub: &str = "";
    assert_eq!(s.contains(sub), true);
}

#[test]
fn string_include_1() {
    let s: &str = "";
    let sub: &str = "a";
    assert_eq!(s.contains(sub), false);
}

#[test]
fn string_include_2() {
    let s: &str = "abc";
    let sub: &str = "";
    assert_eq!(s.contains(sub), true);
}

#[test]
fn string_include_3() {
    let s: &str = "http://x";
    let sub: &str = "://";
    assert_eq!(s.contains(sub), true);
}

#[test]
fn string_include_4() {
    let s: &str = "abc";
    let sub: &str = "ac";
    assert_eq!(s.contains(sub), false);
}

#[test]
fn string_include_5() {
    let s: &str = "\u{65e5}\u{672c}\u{8a9e}";
    let sub: &str = "\u{672c}";
    assert_eq!(s.contains(sub), true);
}

#[test]
fn string_empty_0() {
    let s: &str = "";
    assert_eq!(s.is_empty(), true);
}

#[test]
fn string_empty_1() {
    let s: &str = " ";
    assert_eq!(s.is_empty(), false);
}

#[test]
fn string_empty_2() {
    let s: &str = "a";
    assert_eq!(s.is_empty(), false);
}

#[test]
fn string_empty_3() {
    let s: &str = "\u{0}";
    assert_eq!(s.is_empty(), false);
}

#[test]
fn string_match_regex_0() {
    let s: &str = "";
    let pat: &str = "(?m)x";
    assert_eq!(regex::Regex::new(pat).unwrap().is_match(s), false);
}

#[test]
fn string_match_regex_1() {
    let s: &str = "";
    let pat: &str = "(?m)\\A\\z";
    assert_eq!(regex::Regex::new(pat).unwrap().is_match(s), true);
}

#[test]
fn string_match_regex_2() {
    let s: &str = "a1";
    let pat: &str = "(?m)[0-9]";
    assert_eq!(regex::Regex::new(pat).unwrap().is_match(s), true);
}

#[test]
fn string_match_regex_3() {
    let s: &str = "abc";
    let pat: &str = "(?m)[0-9]";
    assert_eq!(regex::Regex::new(pat).unwrap().is_match(s), false);
}

#[test]
fn string_match_regex_4() {
    let s: &str = "https://x";
    let pat: &str = "(?m)\\Ahttps?://";
    assert_eq!(regex::Regex::new(pat).unwrap().is_match(s), true);
}

#[test]
fn string_match_regex_5() {
    let s: &str = "xhttp://";
    let pat: &str = "(?m)\\Ahttps?://";
    assert_eq!(regex::Regex::new(pat).unwrap().is_match(s), false);
}

#[test]
fn string_match_regex_6() {
    let s: &str = "a\u{a}b";
    let pat: &str = "(?m)^b";
    assert_eq!(regex::Regex::new(pat).unwrap().is_match(s), true);
}

#[test]
fn string_match_regex_7() {
    let s: &str = "a\u{663}b";
    let pat: &str = "(?m)[0-9]";
    assert_eq!(regex::Regex::new(pat).unwrap().is_match(s), false);
}

#[test]
fn string_reverse_0() {
    let s: &str = "";
    assert_eq!(s.chars().rev().collect::<String>(), "");
}

#[test]
fn string_reverse_1() {
    let s: &str = "abc";
    assert_eq!(s.chars().rev().collect::<String>(), "cba");
}

#[test]
fn string_reverse_2() {
    let s: &str = "h\u{e9}llo";
    assert_eq!(s.chars().rev().collect::<String>(), "oll\u{e9}h");
}

#[test]
fn string_reverse_3() {
    let s: &str = "\u{65e5}\u{672c}";
    assert_eq!(s.chars().rev().collect::<String>(), "\u{672c}\u{65e5}");
}

#[test]
fn string_index_string_0() {
    let s: &str = "";
    let sub: &str = "";
    assert_eq!({ let hay = s; hay.find(sub).map(|b| hay[..b].chars().count() as i64) }, Some(0));
}

#[test]
fn string_index_string_1() {
    let s: &str = "";
    let sub: &str = "a";
    assert_eq!({ let hay = s; hay.find(sub).map(|b| hay[..b].chars().count() as i64) }, None);
}

#[test]
fn string_index_string_2() {
    let s: &str = "hello";
    let sub: &str = "l";
    assert_eq!({ let hay = s; hay.find(sub).map(|b| hay[..b].chars().count() as i64) }, Some(2));
}

#[test]
fn string_index_string_3() {
    let s: &str = "h\u{e9}llo";
    let sub: &str = "l";
    assert_eq!({ let hay = s; hay.find(sub).map(|b| hay[..b].chars().count() as i64) }, Some(2));
}

#[test]
fn string_index_string_4() {
    let s: &str = "\u{65e5}\u{672c}\u{8a9e}";
    let sub: &str = "\u{8a9e}";
    assert_eq!({ let hay = s; hay.find(sub).map(|b| hay[..b].chars().count() as i64) }, Some(2));
}

#[test]
fn string_index_string_5() {
    let s: &str = "abc";
    let sub: &str = "";
    assert_eq!({ let hay = s; hay.find(sub).map(|b| hay[..b].chars().count() as i64) }, Some(0));
}

#[test]
fn string_index_string_6() {
    let s: &str = "abc";
    let sub: &str = "d";
    assert_eq!({ let hay = s; hay.find(sub).map(|b| hay[..b].chars().count() as i64) }, None);
}

#[test]
fn string_split_string_length_0() {
    let s: &str = "";
    let sep: &str = ",";
    assert_eq!({ let mut v: Vec<String> = s.split(sep).map(|p| p.to_string()).collect(); while v.last().is_some_and(|l| l.is_empty()) { v.pop(); } v.len() as i64 }, 0);
}

#[test]
fn string_split_string_length_1() {
    let s: &str = "a,b";
    let sep: &str = ",";
    assert_eq!({ let mut v: Vec<String> = s.split(sep).map(|p| p.to_string()).collect(); while v.last().is_some_and(|l| l.is_empty()) { v.pop(); } v.len() as i64 }, 2);
}

#[test]
fn string_split_string_length_2() {
    let s: &str = "a,b,,";
    let sep: &str = ",";
    assert_eq!({ let mut v: Vec<String> = s.split(sep).map(|p| p.to_string()).collect(); while v.last().is_some_and(|l| l.is_empty()) { v.pop(); } v.len() as i64 }, 2);
}

#[test]
fn string_split_string_length_3() {
    let s: &str = ",a";
    let sep: &str = ",";
    assert_eq!({ let mut v: Vec<String> = s.split(sep).map(|p| p.to_string()).collect(); while v.last().is_some_and(|l| l.is_empty()) { v.pop(); } v.len() as i64 }, 2);
}

#[test]
fn string_split_string_length_4() {
    let s: &str = ",,";
    let sep: &str = ",";
    assert_eq!({ let mut v: Vec<String> = s.split(sep).map(|p| p.to_string()).collect(); while v.last().is_some_and(|l| l.is_empty()) { v.pop(); } v.len() as i64 }, 0);
}

#[test]
fn string_split_string_length_5() {
    let s: &str = "a--b";
    let sep: &str = "--";
    assert_eq!({ let mut v: Vec<String> = s.split(sep).map(|p| p.to_string()).collect(); while v.last().is_some_and(|l| l.is_empty()) { v.pop(); } v.len() as i64 }, 2);
}

#[test]
fn string_split_string_length_6() {
    let s: &str = "\u{65e5},\u{672c}";
    let sep: &str = ",";
    assert_eq!({ let mut v: Vec<String> = s.split(sep).map(|p| p.to_string()).collect(); while v.last().is_some_and(|l| l.is_empty()) { v.pop(); } v.len() as i64 }, 2);
}

#[test]
fn string_split_string_first_0() {
    let s: &str = "";
    let sep: &str = ",";
    assert_eq!({ let mut v: Vec<String> = s.split(sep).map(|p| p.to_string()).collect(); while v.last().is_some_and(|l| l.is_empty()) { v.pop(); } v.first().cloned() }, None);
}

#[test]
fn string_split_string_first_1() {
    let s: &str = ",a";
    let sep: &str = ",";
    assert_eq!({ let mut v: Vec<String> = s.split(sep).map(|p| p.to_string()).collect(); while v.last().is_some_and(|l| l.is_empty()) { v.pop(); } v.first().cloned() }, Some("".to_string()));
}

#[test]
fn string_split_string_first_2() {
    let s: &str = "a,b";
    let sep: &str = ",";
    assert_eq!({ let mut v: Vec<String> = s.split(sep).map(|p| p.to_string()).collect(); while v.last().is_some_and(|l| l.is_empty()) { v.pop(); } v.first().cloned() }, Some("a".to_string()));
}

#[test]
fn string_split_string_first_3() {
    let s: &str = ",,";
    let sep: &str = ",";
    assert_eq!({ let mut v: Vec<String> = s.split(sep).map(|p| p.to_string()).collect(); while v.last().is_some_and(|l| l.is_empty()) { v.pop(); } v.first().cloned() }, None);
}

#[test]
fn string_split_string_first_4() {
    let s: &str = "\u{65e5},\u{672c}";
    let sep: &str = ",";
    assert_eq!({ let mut v: Vec<String> = s.split(sep).map(|p| p.to_string()).collect(); while v.last().is_some_and(|l| l.is_empty()) { v.pop(); } v.first().cloned() }, Some("\u{65e5}".to_string()));
}

#[test]
fn string_split_string_last_0() {
    let s: &str = "";
    let sep: &str = ",";
    assert_eq!({ let mut v: Vec<String> = s.split(sep).map(|p| p.to_string()).collect(); while v.last().is_some_and(|l| l.is_empty()) { v.pop(); } v.last().cloned() }, None);
}

#[test]
fn string_split_string_last_1() {
    let s: &str = "a,b";
    let sep: &str = ",";
    assert_eq!({ let mut v: Vec<String> = s.split(sep).map(|p| p.to_string()).collect(); while v.last().is_some_and(|l| l.is_empty()) { v.pop(); } v.last().cloned() }, Some("b".to_string()));
}

#[test]
fn string_split_string_last_2() {
    let s: &str = "a,b,,";
    let sep: &str = ",";
    assert_eq!({ let mut v: Vec<String> = s.split(sep).map(|p| p.to_string()).collect(); while v.last().is_some_and(|l| l.is_empty()) { v.pop(); } v.last().cloned() }, Some("b".to_string()));
}

#[test]
fn string_split_string_last_3() {
    let s: &str = ",a";
    let sep: &str = ",";
    assert_eq!({ let mut v: Vec<String> = s.split(sep).map(|p| p.to_string()).collect(); while v.last().is_some_and(|l| l.is_empty()) { v.pop(); } v.last().cloned() }, Some("a".to_string()));
}

#[test]
fn string_split_string_last_4() {
    let s: &str = "\u{65e5},\u{672c}";
    let sep: &str = ",";
    assert_eq!({ let mut v: Vec<String> = s.split(sep).map(|p| p.to_string()).collect(); while v.last().is_some_and(|l| l.is_empty()) { v.pop(); } v.last().cloned() }, Some("\u{672c}".to_string()));
}

#[test]
fn string_tr_0() {
    let s: &str = "";
    let from: &str = "a";
    let to: &str = "b";
    assert_eq!(s.chars().map(|c| match from.chars().position(|f| f == c) { Some(i) => to.chars().nth(i).unwrap(), None => c }).collect::<String>(), "");
}

#[test]
fn string_tr_1() {
    let s: &str = "hello";
    let from: &str = "el";
    let to: &str = "ip";
    assert_eq!(s.chars().map(|c| match from.chars().position(|f| f == c) { Some(i) => to.chars().nth(i).unwrap(), None => c }).collect::<String>(), "hippo");
}

#[test]
fn string_tr_2() {
    let s: &str = "abc";
    let from: &str = "abc";
    let to: &str = "xyz";
    assert_eq!(s.chars().map(|c| match from.chars().position(|f| f == c) { Some(i) => to.chars().nth(i).unwrap(), None => c }).collect::<String>(), "xyz");
}

#[test]
fn string_tr_3() {
    let s: &str = "\u{65e5}\u{672c}";
    let from: &str = "\u{65e5}";
    let to: &str = "\u{6708}";
    assert_eq!(s.chars().map(|c| match from.chars().position(|f| f == c) { Some(i) => to.chars().nth(i).unwrap(), None => c }).collect::<String>(), "\u{6708}\u{672c}");
}

#[test]
fn string_tr_4() {
    let s: &str = "aaa";
    let from: &str = "a";
    let to: &str = "b";
    assert_eq!(s.chars().map(|c| match from.chars().position(|f| f == c) { Some(i) => to.chars().nth(i).unwrap(), None => c }).collect::<String>(), "bbb");
}

#[test]
fn string_tr_5() {
    let s: &str = "a-b";
    let from: &str = "-";
    let to: &str = "_";
    assert_eq!(s.chars().map(|c| match from.chars().position(|f| f == c) { Some(i) => to.chars().nth(i).unwrap(), None => c }).collect::<String>(), "a_b");
}

#[test]
fn string_tr_6() {
    let s: &str = "a-b";
    let from: &str = "a-";
    let to: &str = "x_";
    assert_eq!(s.chars().map(|c| match from.chars().position(|f| f == c) { Some(i) => to.chars().nth(i).unwrap(), None => c }).collect::<String>(), "x_b");
}

#[test]
fn string_delete_0() {
    let s: &str = "";
    let set: &str = "a";
    assert_eq!(s.chars().filter(|c| !set.contains(*c)).collect::<String>(), "");
}

#[test]
fn string_delete_1() {
    let s: &str = "hello";
    let set: &str = "l";
    assert_eq!(s.chars().filter(|c| !set.contains(*c)).collect::<String>(), "heo");
}

#[test]
fn string_delete_2() {
    let s: &str = "hello";
    let set: &str = "lo";
    assert_eq!(s.chars().filter(|c| !set.contains(*c)).collect::<String>(), "he");
}

#[test]
fn string_delete_3() {
    let s: &str = "\u{65e5}\u{672c}\u{8a9e}";
    let set: &str = "\u{672c}";
    assert_eq!(s.chars().filter(|c| !set.contains(*c)).collect::<String>(), "\u{65e5}\u{8a9e}");
}

#[test]
fn string_delete_4() {
    let s: &str = "abc";
    let set: &str = "x";
    assert_eq!(s.chars().filter(|c| !set.contains(*c)).collect::<String>(), "abc");
}

#[test]
fn string_delete_5() {
    let s: &str = "a-b";
    let set: &str = "-";
    assert_eq!(s.chars().filter(|c| !set.contains(*c)).collect::<String>(), "ab");
}

#[test]
fn string_delete_6() {
    let s: &str = "a-b_c";
    let set: &str = "-_";
    assert_eq!(s.chars().filter(|c| !set.contains(*c)).collect::<String>(), "abc");
}

#[test]
fn string_squeeze_0() {
    let s: &str = "";
    assert_eq!({ let mut o = String::new(); let mut last: Option<char> = None; for c in s.chars() { if last != Some(c) { o.push(c); } last = Some(c); } o }, "");
}

#[test]
fn string_squeeze_1() {
    let s: &str = "aaabbb";
    assert_eq!({ let mut o = String::new(); let mut last: Option<char> = None; for c in s.chars() { if last != Some(c) { o.push(c); } last = Some(c); } o }, "ab");
}

#[test]
fn string_squeeze_2() {
    let s: &str = "abc";
    assert_eq!({ let mut o = String::new(); let mut last: Option<char> = None; for c in s.chars() { if last != Some(c) { o.push(c); } last = Some(c); } o }, "abc");
}

#[test]
fn string_squeeze_3() {
    let s: &str = "aabbaa";
    assert_eq!({ let mut o = String::new(); let mut last: Option<char> = None; for c in s.chars() { if last != Some(c) { o.push(c); } last = Some(c); } o }, "aba");
}

#[test]
fn string_squeeze_4() {
    let s: &str = "\u{e9}\u{e9}a";
    assert_eq!({ let mut o = String::new(); let mut last: Option<char> = None; for c in s.chars() { if last != Some(c) { o.push(c); } last = Some(c); } o }, "\u{e9}a");
}

#[test]
fn string_squeeze_5() {
    let s: &str = "  x  ";
    assert_eq!({ let mut o = String::new(); let mut last: Option<char> = None; for c in s.chars() { if last != Some(c) { o.push(c); } last = Some(c); } o }, " x ");
}

#[test]
fn string_to_i_0() {
    let s: &str = "";
    assert_eq!(str_to_i(s, "t").unwrap(), 0);
}

#[test]
fn string_to_i_1() {
    let s: &str = "42";
    assert_eq!(str_to_i(s, "t").unwrap(), 42);
}

#[test]
fn string_to_i_2() {
    let s: &str = "  -42xyz";
    assert_eq!(str_to_i(s, "t").unwrap(), -42);
}

#[test]
fn string_to_i_3() {
    let s: &str = "\u{a} 7";
    assert_eq!(str_to_i(s, "t").unwrap(), 7);
}

#[test]
fn string_to_i_4() {
    let s: &str = "1_000";
    assert_eq!(str_to_i(s, "t").unwrap(), 1000);
}

#[test]
fn string_to_i_5() {
    let s: &str = "1__0";
    assert_eq!(str_to_i(s, "t").unwrap(), 1);
}

#[test]
fn string_to_i_6() {
    let s: &str = "1_";
    assert_eq!(str_to_i(s, "t").unwrap(), 1);
}

#[test]
fn string_to_i_7() {
    let s: &str = "_1";
    assert_eq!(str_to_i(s, "t").unwrap(), 0);
}

#[test]
fn string_to_i_8() {
    let s: &str = "+5";
    assert_eq!(str_to_i(s, "t").unwrap(), 5);
}

#[test]
fn string_to_i_9() {
    let s: &str = "+-5";
    assert_eq!(str_to_i(s, "t").unwrap(), 0);
}

#[test]
fn string_to_i_10() {
    let s: &str = "- 4";
    assert_eq!(str_to_i(s, "t").unwrap(), 0);
}

#[test]
fn string_to_i_11() {
    let s: &str = "0x1A";
    assert_eq!(str_to_i(s, "t").unwrap(), 0);
}

#[test]
fn string_to_i_12() {
    let s: &str = "\u{663}";
    assert_eq!(str_to_i(s, "t").unwrap(), 0);
}

#[test]
fn string_to_i_13() {
    let s: &str = "007";
    assert_eq!(str_to_i(s, "t").unwrap(), 7);
}

#[test]
fn string_to_i_14() {
    let s: &str = "12abc";
    assert_eq!(str_to_i(s, "t").unwrap(), 12);
}

#[test]
fn string_to_i_15() {
    let s: &str = "9223372036854775807";
    assert_eq!(str_to_i(s, "t").unwrap(), 9223372036854775807);
}

#[test]
fn string_to_i_16() {
    let s: &str = "-9223372036854775808";
    assert_eq!(str_to_i(s, "t").unwrap(), -9223372036854775808);
}

#[test]
fn string_split_string_int_length_0() {
    let s: &str = "";
    let sep: &str = ",";
    let limit: i64 = 2;
    assert_eq!({ let v: Vec<String> = if s.is_empty() { vec![] } else if limit > 0 { s.splitn(limit as usize, sep).map(|p| p.to_string()).collect() } else { s.split(sep).map(|p| p.to_string()).collect() }; v.len() as i64 }, 0);
}

#[test]
fn string_split_string_int_length_1() {
    let s: &str = "";
    let sep: &str = ",";
    let limit: i64 = -1;
    assert_eq!({ let v: Vec<String> = if s.is_empty() { vec![] } else if limit > 0 { s.splitn(limit as usize, sep).map(|p| p.to_string()).collect() } else { s.split(sep).map(|p| p.to_string()).collect() }; v.len() as i64 }, 0);
}

#[test]
fn string_split_string_int_length_2() {
    let s: &str = "a,b,c";
    let sep: &str = ",";
    let limit: i64 = 2;
    assert_eq!({ let v: Vec<String> = if s.is_empty() { vec![] } else if limit > 0 { s.splitn(limit as usize, sep).map(|p| p.to_string()).collect() } else { s.split(sep).map(|p| p.to_string()).collect() }; v.len() as i64 }, 2);
}

#[test]
fn string_split_string_int_length_3() {
    let s: &str = "a,b,,";
    let sep: &str = ",";
    let limit: i64 = 2;
    assert_eq!({ let v: Vec<String> = if s.is_empty() { vec![] } else if limit > 0 { s.splitn(limit as usize, sep).map(|p| p.to_string()).collect() } else { s.split(sep).map(|p| p.to_string()).collect() }; v.len() as i64 }, 2);
}

#[test]
fn string_split_string_int_length_4() {
    let s: &str = "a,b,,";
    let sep: &str = ",";
    let limit: i64 = -1;
    assert_eq!({ let v: Vec<String> = if s.is_empty() { vec![] } else if limit > 0 { s.splitn(limit as usize, sep).map(|p| p.to_string()).collect() } else { s.split(sep).map(|p| p.to_string()).collect() }; v.len() as i64 }, 4);
}

#[test]
fn string_split_string_int_length_5() {
    let s: &str = ",a";
    let sep: &str = ",";
    let limit: i64 = 2;
    assert_eq!({ let v: Vec<String> = if s.is_empty() { vec![] } else if limit > 0 { s.splitn(limit as usize, sep).map(|p| p.to_string()).collect() } else { s.split(sep).map(|p| p.to_string()).collect() }; v.len() as i64 }, 2);
}

#[test]
fn string_split_string_int_length_6() {
    let s: &str = "abc";
    let sep: &str = ",";
    let limit: i64 = 2;
    assert_eq!({ let v: Vec<String> = if s.is_empty() { vec![] } else if limit > 0 { s.splitn(limit as usize, sep).map(|p| p.to_string()).collect() } else { s.split(sep).map(|p| p.to_string()).collect() }; v.len() as i64 }, 1);
}

#[test]
fn string_split_string_int_length_7() {
    let s: &str = "a,b";
    let sep: &str = ",";
    let limit: i64 = 1;
    assert_eq!({ let v: Vec<String> = if s.is_empty() { vec![] } else if limit > 0 { s.splitn(limit as usize, sep).map(|p| p.to_string()).collect() } else { s.split(sep).map(|p| p.to_string()).collect() }; v.len() as i64 }, 1);
}

#[test]
fn string_split_string_int_length_8() {
    let s: &str = "a,,";
    let sep: &str = ",";
    let limit: i64 = -1;
    assert_eq!({ let v: Vec<String> = if s.is_empty() { vec![] } else if limit > 0 { s.splitn(limit as usize, sep).map(|p| p.to_string()).collect() } else { s.split(sep).map(|p| p.to_string()).collect() }; v.len() as i64 }, 3);
}

#[test]
fn string_split_string_int_last_0() {
    let s: &str = "";
    let sep: &str = ",";
    let limit: i64 = 2;
    assert_eq!({ let v: Vec<String> = if s.is_empty() { vec![] } else if limit > 0 { s.splitn(limit as usize, sep).map(|p| p.to_string()).collect() } else { s.split(sep).map(|p| p.to_string()).collect() }; v.last().cloned() }, None);
}

#[test]
fn string_split_string_int_last_1() {
    let s: &str = "a,b,c";
    let sep: &str = ",";
    let limit: i64 = 2;
    assert_eq!({ let v: Vec<String> = if s.is_empty() { vec![] } else if limit > 0 { s.splitn(limit as usize, sep).map(|p| p.to_string()).collect() } else { s.split(sep).map(|p| p.to_string()).collect() }; v.last().cloned() }, Some("b,c".to_string()));
}

#[test]
fn string_split_string_int_last_2() {
    let s: &str = "a,b,,";
    let sep: &str = ",";
    let limit: i64 = -1;
    assert_eq!({ let v: Vec<String> = if s.is_empty() { vec![] } else if limit > 0 { s.splitn(limit as usize, sep).map(|p| p.to_string()).collect() } else { s.split(sep).map(|p| p.to_string()).collect() }; v.last().cloned() }, Some("".to_string()));
}

#[test]
fn string_split_string_int_last_3() {
    let s: &str = "abc";
    let sep: &str = ",";
    let limit: i64 = 2;
    assert_eq!({ let v: Vec<String> = if s.is_empty() { vec![] } else if limit > 0 { s.splitn(limit as usize, sep).map(|p| p.to_string()).collect() } else { s.split(sep).map(|p| p.to_string()).collect() }; v.last().cloned() }, Some("abc".to_string()));
}

#[test]
fn string_split_string_int_last_4() {
    let s: &str = "a://b";
    let sep: &str = "://";
    let limit: i64 = 2;
    assert_eq!({ let v: Vec<String> = if s.is_empty() { vec![] } else if limit > 0 { s.splitn(limit as usize, sep).map(|p| p.to_string()).collect() } else { s.split(sep).map(|p| p.to_string()).collect() }; v.last().cloned() }, Some("b".to_string()));
}

#[test]
fn string_partition_string_first_0() {
    let s: &str = "";
    let sep: &str = "/";
    assert_eq!(match s.find(sep) { Some(i) => s[..i].to_string(), None => s.to_string() }, "");
}

#[test]
fn string_partition_string_first_1() {
    let s: &str = "a/b/c";
    let sep: &str = "/";
    assert_eq!(match s.find(sep) { Some(i) => s[..i].to_string(), None => s.to_string() }, "a");
}

#[test]
fn string_partition_string_first_2() {
    let s: &str = "abc";
    let sep: &str = "/";
    assert_eq!(match s.find(sep) { Some(i) => s[..i].to_string(), None => s.to_string() }, "abc");
}

#[test]
fn string_partition_string_first_3() {
    let s: &str = "a//b";
    let sep: &str = "//";
    assert_eq!(match s.find(sep) { Some(i) => s[..i].to_string(), None => s.to_string() }, "a");
}

#[test]
fn string_partition_string_first_4() {
    let s: &str = "\u{65e5}/\u{672c}";
    let sep: &str = "/";
    assert_eq!(match s.find(sep) { Some(i) => s[..i].to_string(), None => s.to_string() }, "\u{65e5}");
}

#[test]
fn string_partition_string_first_5() {
    let s: &str = "abc";
    let sep: &str = "";
    assert_eq!(match s.find(sep) { Some(i) => s[..i].to_string(), None => s.to_string() }, "");
}

#[test]
fn string_partition_string_last_0() {
    let s: &str = "";
    let sep: &str = "/";
    assert_eq!(match s.find(sep) { Some(i) => s[i + sep.len()..].to_string(), None => String::new() }, "");
}

#[test]
fn string_partition_string_last_1() {
    let s: &str = "a/b/c";
    let sep: &str = "/";
    assert_eq!(match s.find(sep) { Some(i) => s[i + sep.len()..].to_string(), None => String::new() }, "b/c");
}

#[test]
fn string_partition_string_last_2() {
    let s: &str = "abc";
    let sep: &str = "/";
    assert_eq!(match s.find(sep) { Some(i) => s[i + sep.len()..].to_string(), None => String::new() }, "");
}

#[test]
fn string_partition_string_last_3() {
    let s: &str = "a//b";
    let sep: &str = "//";
    assert_eq!(match s.find(sep) { Some(i) => s[i + sep.len()..].to_string(), None => String::new() }, "b");
}

#[test]
fn string_partition_string_last_4() {
    let s: &str = "\u{65e5}/\u{672c}";
    let sep: &str = "/";
    assert_eq!(match s.find(sep) { Some(i) => s[i + sep.len()..].to_string(), None => String::new() }, "\u{672c}");
}

#[test]
fn string_partition_string_last_5() {
    let s: &str = "abc";
    let sep: &str = "";
    assert_eq!(match s.find(sep) { Some(i) => s[i + sep.len()..].to_string(), None => String::new() }, "abc");
}

#[test]
fn string_lines_length_0() {
    let s: &str = "";
    assert_eq!(s.split_inclusive('\n').count() as i64, 0);
}

#[test]
fn string_lines_length_1() {
    let s: &str = "a";
    assert_eq!(s.split_inclusive('\n').count() as i64, 1);
}

#[test]
fn string_lines_length_2() {
    let s: &str = "a\u{a}";
    assert_eq!(s.split_inclusive('\n').count() as i64, 1);
}

#[test]
fn string_lines_length_3() {
    let s: &str = "a\u{a}b";
    assert_eq!(s.split_inclusive('\n').count() as i64, 2);
}

#[test]
fn string_lines_length_4() {
    let s: &str = "a\u{a}\u{a}";
    assert_eq!(s.split_inclusive('\n').count() as i64, 2);
}

#[test]
fn string_lines_length_5() {
    let s: &str = "\u{a}";
    assert_eq!(s.split_inclusive('\n').count() as i64, 1);
}

#[test]
fn string_lines_length_6() {
    let s: &str = "a\u{d}\u{a}b";
    assert_eq!(s.split_inclusive('\n').count() as i64, 2);
}

#[test]
fn string_int_int_0() {
    let s: &str = "hello";
    let start: i64 = 1;
    let len: i64 = 3;
    assert_eq!({ let cs: Vec<char> = s.chars().collect(); let n = cs.len() as i64; let mut st = start; if st < 0 { st += n; } if st < 0 || st > n || len < 0 { None } else { let en = st.saturating_add(len).min(n); Some(cs[st as usize..en as usize].iter().collect::<String>()) } }, Some("ell".to_string()));
}

#[test]
fn string_int_int_1() {
    let s: &str = "hello";
    let start: i64 = -3;
    let len: i64 = 2;
    assert_eq!({ let cs: Vec<char> = s.chars().collect(); let n = cs.len() as i64; let mut st = start; if st < 0 { st += n; } if st < 0 || st > n || len < 0 { None } else { let en = st.saturating_add(len).min(n); Some(cs[st as usize..en as usize].iter().collect::<String>()) } }, Some("ll".to_string()));
}

#[test]
fn string_int_int_2() {
    let s: &str = "hello";
    let start: i64 = 5;
    let len: i64 = 1;
    assert_eq!({ let cs: Vec<char> = s.chars().collect(); let n = cs.len() as i64; let mut st = start; if st < 0 { st += n; } if st < 0 || st > n || len < 0 { None } else { let en = st.saturating_add(len).min(n); Some(cs[st as usize..en as usize].iter().collect::<String>()) } }, Some("".to_string()));
}

#[test]
fn string_int_int_3() {
    let s: &str = "hello";
    let start: i64 = 6;
    let len: i64 = 1;
    assert_eq!({ let cs: Vec<char> = s.chars().collect(); let n = cs.len() as i64; let mut st = start; if st < 0 { st += n; } if st < 0 || st > n || len < 0 { None } else { let en = st.saturating_add(len).min(n); Some(cs[st as usize..en as usize].iter().collect::<String>()) } }, None);
}

#[test]
fn string_int_int_4() {
    let s: &str = "h\u{e9}llo";
    let start: i64 = 1;
    let len: i64 = 2;
    assert_eq!({ let cs: Vec<char> = s.chars().collect(); let n = cs.len() as i64; let mut st = start; if st < 0 { st += n; } if st < 0 || st > n || len < 0 { None } else { let en = st.saturating_add(len).min(n); Some(cs[st as usize..en as usize].iter().collect::<String>()) } }, Some("\u{e9}l".to_string()));
}

#[test]
fn string_int_int_5() {
    let s: &str = "hello";
    let start: i64 = 1;
    let len: i64 = -1;
    assert_eq!({ let cs: Vec<char> = s.chars().collect(); let n = cs.len() as i64; let mut st = start; if st < 0 { st += n; } if st < 0 || st > n || len < 0 { None } else { let en = st.saturating_add(len).min(n); Some(cs[st as usize..en as usize].iter().collect::<String>()) } }, None);
}

#[test]
fn string_int_int_6() {
    let s: &str = "hello";
    let start: i64 = 3;
    let len: i64 = 100;
    assert_eq!({ let cs: Vec<char> = s.chars().collect(); let n = cs.len() as i64; let mut st = start; if st < 0 { st += n; } if st < 0 || st > n || len < 0 { None } else { let en = st.saturating_add(len).min(n); Some(cs[st as usize..en as usize].iter().collect::<String>()) } }, Some("lo".to_string()));
}

#[test]
fn string_int_int_7() {
    let s: &str = "";
    let start: i64 = 0;
    let len: i64 = 1;
    assert_eq!({ let cs: Vec<char> = s.chars().collect(); let n = cs.len() as i64; let mut st = start; if st < 0 { st += n; } if st < 0 || st > n || len < 0 { None } else { let en = st.saturating_add(len).min(n); Some(cs[st as usize..en as usize].iter().collect::<String>()) } }, Some("".to_string()));
}

#[test]
fn string_int_int_8() {
    let s: &str = "";
    let start: i64 = 1;
    let len: i64 = 1;
    assert_eq!({ let cs: Vec<char> = s.chars().collect(); let n = cs.len() as i64; let mut st = start; if st < 0 { st += n; } if st < 0 || st > n || len < 0 { None } else { let en = st.saturating_add(len).min(n); Some(cs[st as usize..en as usize].iter().collect::<String>()) } }, None);
}

#[test]
fn string_int_int_9() {
    let s: &str = "\u{65e5}\u{672c}\u{8a9e}";
    let start: i64 = 1;
    let len: i64 = 1;
    assert_eq!({ let cs: Vec<char> = s.chars().collect(); let n = cs.len() as i64; let mut st = start; if st < 0 { st += n; } if st < 0 || st > n || len < 0 { None } else { let en = st.saturating_add(len).min(n); Some(cs[st as usize..en as usize].iter().collect::<String>()) } }, Some("\u{672c}".to_string()));
}

#[test]
fn string_int_int_10() {
    let s: &str = "hello";
    let start: i64 = -6;
    let len: i64 = 2;
    assert_eq!({ let cs: Vec<char> = s.chars().collect(); let n = cs.len() as i64; let mut st = start; if st < 0 { st += n; } if st < 0 || st > n || len < 0 { None } else { let en = st.saturating_add(len).min(n); Some(cs[st as usize..en as usize].iter().collect::<String>()) } }, None);
}

#[test]
fn string_int_0() {
    let s: &str = "abc";
    let idx: i64 = 0;
    assert_eq!({ let cs: Vec<char> = s.chars().collect(); let n = cs.len() as i64; let j = if idx < 0 { idx + n } else { idx }; if j >= 0 && j < n { Some(cs[j as usize].to_string()) } else { None } }, Some("a".to_string()));
}

#[test]
fn string_int_1() {
    let s: &str = "abc";
    let idx: i64 = -1;
    assert_eq!({ let cs: Vec<char> = s.chars().collect(); let n = cs.len() as i64; let j = if idx < 0 { idx + n } else { idx }; if j >= 0 && j < n { Some(cs[j as usize].to_string()) } else { None } }, Some("c".to_string()));
}

#[test]
fn string_int_2() {
    let s: &str = "abc";
    let idx: i64 = 3;
    assert_eq!({ let cs: Vec<char> = s.chars().collect(); let n = cs.len() as i64; let j = if idx < 0 { idx + n } else { idx }; if j >= 0 && j < n { Some(cs[j as usize].to_string()) } else { None } }, None);
}

#[test]
fn string_int_3() {
    let s: &str = "abc";
    let idx: i64 = -4;
    assert_eq!({ let cs: Vec<char> = s.chars().collect(); let n = cs.len() as i64; let j = if idx < 0 { idx + n } else { idx }; if j >= 0 && j < n { Some(cs[j as usize].to_string()) } else { None } }, None);
}

#[test]
fn string_int_4() {
    let s: &str = "h\u{e9}y";
    let idx: i64 = 1;
    assert_eq!({ let cs: Vec<char> = s.chars().collect(); let n = cs.len() as i64; let j = if idx < 0 { idx + n } else { idx }; if j >= 0 && j < n { Some(cs[j as usize].to_string()) } else { None } }, Some("\u{e9}".to_string()));
}

#[test]
fn string_int_5() {
    let s: &str = "";
    let idx: i64 = 0;
    assert_eq!({ let cs: Vec<char> = s.chars().collect(); let n = cs.len() as i64; let j = if idx < 0 { idx + n } else { idx }; if j >= 0 && j < n { Some(cs[j as usize].to_string()) } else { None } }, None);
}

#[test]
fn string_0() {
    let s: &str = "ab";
    let count: i64 = 3;
    assert_eq!(if count < 0 { Err(()) } else { Ok(s.repeat(count as usize)) }.unwrap(), "ababab");
}

#[test]
fn string_1() {
    let s: &str = "ab";
    let count: i64 = 0;
    assert_eq!(if count < 0 { Err(()) } else { Ok(s.repeat(count as usize)) }.unwrap(), "");
}

#[test]
fn string_2() {
    let s: &str = "";
    let count: i64 = 5;
    assert_eq!(if count < 0 { Err(()) } else { Ok(s.repeat(count as usize)) }.unwrap(), "");
}

#[test]
fn string_3() {
    let s: &str = "\u{65e5}";
    let count: i64 = 2;
    assert_eq!(if count < 0 { Err(()) } else { Ok(s.repeat(count as usize)) }.unwrap(), "\u{65e5}\u{65e5}");
}

#[test]
fn string_4() {
    let s: &str = "ab";
    let count: i64 = -1;
    assert!(if count < 0 { Err(()) } else { Ok(s.repeat(count as usize)) }.is_err());
}

#[test]
fn integer_string_10_0() {
    let s: &str = "42";
    let base: i64 = 10;
    assert_eq!({ assert_eq!(base, 10); str_to_int(s, "t") }.unwrap(), 42);
}

#[test]
fn integer_string_10_1() {
    let s: &str = "  42  ";
    let base: i64 = 10;
    assert_eq!({ assert_eq!(base, 10); str_to_int(s, "t") }.unwrap(), 42);
}

#[test]
fn integer_string_10_2() {
    let s: &str = "-7";
    let base: i64 = 10;
    assert_eq!({ assert_eq!(base, 10); str_to_int(s, "t") }.unwrap(), -7);
}

#[test]
fn integer_string_10_3() {
    let s: &str = "+5";
    let base: i64 = 10;
    assert_eq!({ assert_eq!(base, 10); str_to_int(s, "t") }.unwrap(), 5);
}

#[test]
fn integer_string_10_4() {
    let s: &str = "1_000";
    let base: i64 = 10;
    assert_eq!({ assert_eq!(base, 10); str_to_int(s, "t") }.unwrap(), 1000);
}

#[test]
fn integer_string_10_5() {
    let s: &str = "007";
    let base: i64 = 10;
    assert_eq!({ assert_eq!(base, 10); str_to_int(s, "t") }.unwrap(), 7);
}

#[test]
fn integer_string_10_6() {
    let s: &str = "9223372036854775807";
    let base: i64 = 10;
    assert_eq!({ assert_eq!(base, 10); str_to_int(s, "t") }.unwrap(), 9223372036854775807);
}

#[test]
fn integer_string_10_7() {
    let s: &str = "";
    let base: i64 = 10;
    assert!({ assert_eq!(base, 10); str_to_int(s, "t") }.is_err());
}

#[test]
fn integer_string_10_8() {
    let s: &str = " ";
    let base: i64 = 10;
    assert!({ assert_eq!(base, 10); str_to_int(s, "t") }.is_err());
}

#[test]
fn integer_string_10_9() {
    let s: &str = "4 2";
    let base: i64 = 10;
    assert!({ assert_eq!(base, 10); str_to_int(s, "t") }.is_err());
}

#[test]
fn integer_string_10_10() {
    let s: &str = "1__0";
    let base: i64 = 10;
    assert!({ assert_eq!(base, 10); str_to_int(s, "t") }.is_err());
}

#[test]
fn integer_string_10_11() {
    let s: &str = "_1";
    let base: i64 = 10;
    assert!({ assert_eq!(base, 10); str_to_int(s, "t") }.is_err());
}

#[test]
fn integer_string_10_12() {
    let s: &str = "1_";
    let base: i64 = 10;
    assert!({ assert_eq!(base, 10); str_to_int(s, "t") }.is_err());
}

#[test]
fn integer_string_10_13() {
    let s: &str = "0x1A";
    let base: i64 = 10;
    assert!({ assert_eq!(base, 10); str_to_int(s, "t") }.is_err());
}

#[test]
fn integer_string_10_14() {
    let s: &str = "12abc";
    let base: i64 = 10;
    assert!({ assert_eq!(base, 10); str_to_int(s, "t") }.is_err());
}

#[test]
fn integer_string_10_15() {
    let s: &str = "- 5";
    let base: i64 = 10;
    assert!({ assert_eq!(base, 10); str_to_int(s, "t") }.is_err());
}

#[test]
fn integer_string_10_16() {
    let s: &str = "\u{663}";
    let base: i64 = 10;
    assert!({ assert_eq!(base, 10); str_to_int(s, "t") }.is_err());
}

#[test]
fn integer_string_10_17() {
    let s: &str = "--5";
    let base: i64 = 10;
    assert!({ assert_eq!(base, 10); str_to_int(s, "t") }.is_err());
}

#[test]
fn string_gsub_regex_bracket_0() {
    let s: &str = "";
    let pat: &str = "(?m)x";
    assert_eq!(regex::Regex::new(pat).unwrap().replace_all(s, |c: &regex::Captures| format!("[{}]", &c[0])).into_owned(), "");
}

#[test]
fn string_gsub_regex_bracket_1() {
    let s: &str = "";
    let pat: &str = "(?m)x*";
    assert_eq!(regex::Regex::new(pat).unwrap().replace_all(s, |c: &regex::Captures| format!("[{}]", &c[0])).into_owned(), "[]");
}

#[test]
fn string_gsub_regex_bracket_2() {
    let s: &str = "abc";
    let pat: &str = "(?m)x*";
    assert_eq!(regex::Regex::new(pat).unwrap().replace_all(s, |c: &regex::Captures| format!("[{}]", &c[0])).into_owned(), "[]a[]b[]c[]");
}

#[test]
fn string_gsub_regex_bracket_3() {
    let s: &str = "a1b22";
    let pat: &str = "(?m)[0-9]+";
    assert_eq!(regex::Regex::new(pat).unwrap().replace_all(s, |c: &regex::Captures| format!("[{}]", &c[0])).into_owned(), "a[1]b[22]");
}

#[test]
fn string_gsub_regex_bracket_4() {
    let s: &str = "h\u{e9}llo";
    let pat: &str = "(?m)\u{e9}";
    assert_eq!(regex::Regex::new(pat).unwrap().replace_all(s, |c: &regex::Captures| format!("[{}]", &c[0])).into_owned(), "h[\u{e9}]llo");
}

#[test]
fn string_gsub_regex_bracket_5() {
    let s: &str = "a\u{a}b";
    let pat: &str = "(?m)^b";
    assert_eq!(regex::Regex::new(pat).unwrap().replace_all(s, |c: &regex::Captures| format!("[{}]", &c[0])).into_owned(), "a\u{a}[b]");
}

#[test]
fn string_sub_regex_bracket_0() {
    let s: &str = "";
    let pat: &str = "(?m)x";
    assert_eq!(regex::Regex::new(pat).unwrap().replace(s, |c: &regex::Captures| format!("[{}]", &c[0])).into_owned(), "");
}

#[test]
fn string_sub_regex_bracket_1() {
    let s: &str = "abc";
    let pat: &str = "(?m)x*";
    assert_eq!(regex::Regex::new(pat).unwrap().replace(s, |c: &regex::Captures| format!("[{}]", &c[0])).into_owned(), "[]abc");
}

#[test]
fn string_sub_regex_bracket_2() {
    let s: &str = "a1b22";
    let pat: &str = "(?m)[0-9]+";
    assert_eq!(regex::Regex::new(pat).unwrap().replace(s, |c: &regex::Captures| format!("[{}]", &c[0])).into_owned(), "a[1]b22");
}

#[test]
fn string_sub_regex_bracket_3() {
    let s: &str = "h\u{e9}llo";
    let pat: &str = "(?m)l+";
    assert_eq!(regex::Regex::new(pat).unwrap().replace(s, |c: &regex::Captures| format!("[{}]", &c[0])).into_owned(), "h\u{e9}[ll]o");
}

#[test]
fn string_gsub_regex_upcase_0() {
    let s: &str = "";
    let pat: &str = "(?m)a";
    assert_eq!(regex::Regex::new(pat).unwrap().replace_all(s, |c: &regex::Captures| c[0].to_uppercase()).into_owned(), "");
}

#[test]
fn string_gsub_regex_upcase_1() {
    let s: &str = "abcabc";
    let pat: &str = "(?m)b";
    assert_eq!(regex::Regex::new(pat).unwrap().replace_all(s, |c: &regex::Captures| c[0].to_uppercase()).into_owned(), "aBcaBc");
}

#[test]
fn string_gsub_regex_upcase_2() {
    let s: &str = "hello world";
    let pat: &str = "(?m)[a-z]+";
    assert_eq!(regex::Regex::new(pat).unwrap().replace_all(s, |c: &regex::Captures| c[0].to_uppercase()).into_owned(), "HELLO WORLD");
}

#[test]
fn string_gsub_regex_upcase_3() {
    let s: &str = "h\u{e9}llo";
    let pat: &str = "(?m)\u{e9}";
    assert_eq!(regex::Regex::new(pat).unwrap().replace_all(s, |c: &regex::Captures| c[0].to_uppercase()).into_owned(), "h\u{c9}llo");
}

#[test]
fn binding_heck_snake_case_0() {
    assert_eq!(heck_snake_case("HelloWorld fooBar"), "hello_world_foo_bar");
}

#[test]
fn binding_heck_snake_case_1() {
    assert_eq!(heck_snake_case("already_snake"), "already_snake");
}

#[test]
fn binding_heck_snake_case_2() {
    assert_eq!(heck_snake_case("  spaced   out  "), "spaced_out");
}

#[test]
fn binding_heck_snake_case_3() {
    assert_eq!(heck_snake_case(""), "");
}

#[test]
fn binding_heck_kebab_case_0() {
    assert_eq!(heck_kebab_case("HelloWorld fooBar"), "hello-world-foo-bar");
}

#[test]
fn binding_heck_kebab_case_1() {
    assert_eq!(heck_kebab_case("snake_case_input"), "snake-case-input");
}

#[test]
fn binding_heck_kebab_case_2() {
    assert_eq!(heck_kebab_case(""), "");
}

#[test]
fn binding_heck_upper_camel_case_0() {
    assert_eq!(heck_upper_camel_case("hello_world foo-bar"), "HelloWorldFooBar");
}

#[test]
fn binding_heck_upper_camel_case_1() {
    assert_eq!(heck_upper_camel_case("HelloWorld fooBar"), "HelloWorldFooBar");
}

#[test]
fn binding_heck_upper_camel_case_2() {
    assert_eq!(heck_upper_camel_case(""), "");
}

#[test]
fn binding_html_valid_selector_p_0() {
    assert_eq!(html_valid_selector_p("h1"), true);
}

#[test]
fn binding_html_valid_selector_p_1() {
    assert_eq!(html_valid_selector_p("ul > li.item"), true);
}

#[test]
fn binding_html_valid_selector_p_2() {
    assert_eq!(html_valid_selector_p("a["), false);
}

#[test]
fn binding_html_select_0() {
    assert_eq!(html_select("<h1>Main   heading</h1>", "h1"), Some(vec!["Main heading".to_string()]));
}

#[test]
fn binding_html_select_1() {
    assert_eq!(html_select("<ul><li>a</li><li>b <b>c</b></li></ul>", "li"), Some(vec!["a".to_string(), "b c".to_string()]));
}

#[test]
fn binding_html_select_2() {
    assert_eq!(html_select("<p>Hello &amp; goodbye</p>", "p"), Some(vec!["Hello & goodbye".to_string()]));
}

#[test]
fn binding_html_select_3() {
    assert_eq!(html_select("<p>x</p>", "h1"), Some(vec![]));
}

#[test]
fn binding_html_select_4() {
    assert_eq!(html_select("", "p"), Some(vec![]));
}

#[test]
fn binding_html_select_5() {
    assert_eq!(html_select("<p>x</p>", "p["), None);
}

#[test]
fn binding_html_attr_0() {
    assert_eq!(html_attr("<a href=\"/one\">1</a><a>2</a><a href=\"/two\">3</a>", "a", "href"), Some(vec!["/one".to_string(), "/two".to_string()]));
}

#[test]
fn binding_html_attr_1() {
    assert_eq!(html_attr("<p>x</p>", "p", "id"), Some(vec![]));
}

#[test]
fn binding_html_attr_2() {
    assert_eq!(html_attr("", "a", "href"), Some(vec![]));
}

#[test]
fn binding_html_attr_3() {
    assert_eq!(html_attr("<a href=\"/x\">y</a>", "a[", "href"), None);
}

#[test]
fn binding_net_addresses_0() {
    assert_eq!(net_addresses("127.0.0.1"), Some(vec!["127.0.0.1".to_string()]));
}

#[test]
fn binding_net_addresses_1() {
    assert_eq!(net_addresses("::1"), Some(vec!["::1".to_string()]));
}

#[test]
fn binding_net_public_address_p_0() {
    assert_eq!(net_public_address_p("8.8.8.8"), true);
}

#[test]
fn binding_net_public_address_p_1() {
    assert_eq!(net_public_address_p("1.1.1.1"), true);
}

#[test]
fn binding_net_public_address_p_2() {
    assert_eq!(net_public_address_p("2606:4700:4700::1111"), true);
}

#[test]
fn binding_net_public_address_p_3() {
    assert_eq!(net_public_address_p("127.0.0.1"), false);
}

#[test]
fn binding_net_public_address_p_4() {
    assert_eq!(net_public_address_p("10.0.0.1"), false);
}

#[test]
fn binding_net_public_address_p_5() {
    assert_eq!(net_public_address_p("192.168.1.1"), false);
}

#[test]
fn binding_net_public_address_p_6() {
    assert_eq!(net_public_address_p("172.16.0.1"), false);
}

#[test]
fn binding_net_public_address_p_7() {
    assert_eq!(net_public_address_p("169.254.169.254"), false);
}

#[test]
fn binding_net_public_address_p_8() {
    assert_eq!(net_public_address_p("100.64.0.1"), false);
}

#[test]
fn binding_net_public_address_p_9() {
    assert_eq!(net_public_address_p("0.0.0.0"), false);
}

#[test]
fn binding_net_public_address_p_10() {
    assert_eq!(net_public_address_p("255.255.255.255"), false);
}

#[test]
fn binding_net_public_address_p_11() {
    assert_eq!(net_public_address_p("224.0.0.1"), false);
}

#[test]
fn binding_net_public_address_p_12() {
    assert_eq!(net_public_address_p("::1"), false);
}

#[test]
fn binding_net_public_address_p_13() {
    assert_eq!(net_public_address_p("fc00::1"), false);
}

#[test]
fn binding_net_public_address_p_14() {
    assert_eq!(net_public_address_p("fe80::1"), false);
}

#[test]
fn binding_net_public_address_p_15() {
    assert_eq!(net_public_address_p("::ffff:127.0.0.1"), false);
}

#[test]
fn binding_net_public_address_p_16() {
    assert_eq!(net_public_address_p("not an ip"), false);
}

#[test]
fn binding_net_public_address_p_17() {
    assert_eq!(net_public_address_p(""), false);
}

#[test]
fn binding_url_valid_p_0() {
    assert_eq!(url_valid_p("https://example.com/a?b=c#d"), true);
}

#[test]
fn binding_url_valid_p_1() {
    assert_eq!(url_valid_p("not a url"), false);
}

#[test]
fn binding_url_valid_p_2() {
    assert_eq!(url_valid_p(""), false);
}

#[test]
fn binding_url_credentials_p_0() {
    assert_eq!(url_credentials_p("http://user:pw@example.com/"), true);
}

#[test]
fn binding_url_credentials_p_1() {
    assert_eq!(url_credentials_p("http://user@example.com/"), true);
}

#[test]
fn binding_url_credentials_p_2() {
    assert_eq!(url_credentials_p("http://example.com/"), false);
}

#[test]
fn binding_url_credentials_p_3() {
    assert_eq!(url_credentials_p("not a url"), false);
}

#[test]
fn binding_url_scheme_0() {
    assert_eq!(url_scheme("HTTPS://example.com"), Some("https".to_string()));
}

#[test]
fn binding_url_scheme_1() {
    assert_eq!(url_scheme("mailto:a@b.c"), Some("mailto".to_string()));
}

#[test]
fn binding_url_scheme_2() {
    assert_eq!(url_scheme("not a url"), None);
}

#[test]
fn binding_url_host_0() {
    assert_eq!(url_host("https://Example.COM:8080/a"), Some("example.com".to_string()));
}

#[test]
fn binding_url_host_1() {
    assert_eq!(url_host("http://[::1]:3000/"), Some("[::1]".to_string()));
}

#[test]
fn binding_url_host_2() {
    assert_eq!(url_host("mailto:a@b.c"), None);
}

#[test]
fn binding_url_host_3() {
    assert_eq!(url_host("not a url"), None);
}

#[test]
fn binding_url_port_0() {
    assert_eq!(url_port("https://example.com"), Some(443));
}

#[test]
fn binding_url_port_1() {
    assert_eq!(url_port("http://example.com:8080/"), Some(8080));
}

#[test]
fn binding_url_port_2() {
    assert_eq!(url_port("http://example.com"), Some(80));
}

#[test]
fn binding_url_port_3() {
    assert_eq!(url_port("file:///etc/hosts"), None);
}

#[test]
fn binding_url_path_0() {
    assert_eq!(url_path("https://example.com"), Some("/".to_string()));
}

#[test]
fn binding_url_path_1() {
    assert_eq!(url_path("https://example.com/a/b?q=1#frag"), Some("/a/b".to_string()));
}

#[test]
fn binding_url_path_2() {
    assert_eq!(url_path("not a url"), None);
}

#[test]
fn binding_url_join_0() {
    assert_eq!(url_join("https://example.com/a/b", "c"), Some("https://example.com/a/c".to_string()));
}

#[test]
fn binding_url_join_1() {
    assert_eq!(url_join("https://example.com/a/b", "/z"), Some("https://example.com/z".to_string()));
}

#[test]
fn binding_url_join_2() {
    assert_eq!(url_join("https://example.com/a/b", "../q"), Some("https://example.com/q".to_string()));
}

#[test]
fn binding_url_join_3() {
    assert_eq!(url_join("https://example.com/a?x=1", "?y=2"), Some("https://example.com/a?y=2".to_string()));
}

#[test]
fn binding_url_join_4() {
    assert_eq!(url_join("https://example.com/", "http://other.org/p"), Some("http://other.org/p".to_string()));
}

#[test]
fn binding_url_join_5() {
    assert_eq!(url_join("not a url", "x"), None);
}
